# Generated by Django 4.2.11 on 2024-03-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('course', models.IntegerField(default=0, null=True)),
                ('grade', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
