# Generated by Django 4.2.11 on 2024-03-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
    ]
