# Generated by Django 4.2.13 on 2024-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='quiz_done',
            field=models.BooleanField(default=False),
        ),
    ]
