# Generated by Django 4.2.11 on 2024-03-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
