# Generated by Django 4.2.13 on 2024-06-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_courseprogress_quiz_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='feedback_sent',
            field=models.BooleanField(default=False),
        ),
    ]
