# Generated by Django 4.2.11 on 2024-03-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_courseprogress_is_completed_courseprogress_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='course_level',
            field=models.IntegerField(default=0),
        ),
    ]
