# Generated by Django 4.2.11 on 2024-04-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTrialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('level', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('question', models.CharField(max_length=500, null=True)),
                ('situation', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTrialAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('fin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.financialtrialmodel')),
            ],
        ),
    ]
