# Generated by Django 4.2.10 on 2024-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='category',
            field=models.CharField(default='Money', max_length=255),
        ),
    ]
