# Generated by Django 4.2.11 on 2024-04-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='is_free',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
