# Generated by Django 4.2.10 on 2024-03-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursemodel_category_lessonmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='lesson_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
