# Generated by Django 4.2.11 on 2024-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lessonmodel_lesson_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0, null=True)),
                ('question', models.CharField(max_length=255, null=True)),
                ('answer_one', models.CharField(max_length=255, null=True)),
                ('answer_two', models.CharField(max_length=255, null=True)),
                ('answer_three', models.CharField(max_length=255, null=True)),
                ('answer_four', models.CharField(max_length=255, null=True)),
                ('correct_answer', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
