# Generated by Django 4.2.10 on 2024-03-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lessonmodel_coursemodel_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel'),
        ),
    ]
