# Generated by Django 4.2.11 on 2024-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_quizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_num',
            field=models.IntegerField(default=0),
        ),
    ]
