# Generated by Django 4.2.11 on 2024-03-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursemodel_course_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='answer_four',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='answer_one',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='answer_three',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='answer_two',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='correct_answer',
        ),
        migrations.CreateModel(
            name='QuizAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.quizmodel')),
            ],
        ),
    ]
