# Generated by Django 4.2.11 on 2024-03-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_quizmodel_answer_four_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizProgress',
        ),
    ]
