# Generated by Django 4.2.11 on 2024-03-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_delete_quizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
