# Generated by Django 4.2.11 on 2024-03-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lessonmodel_lesson_num'),
        ('user', '0002_user_bookmarked_courses_alter_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarked_courses',
            field=models.ManyToManyField(blank=True, to='course.coursemodel'),
        ),
    ]
