# Generated by Django 4.2.10 on 2024-02-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_verified_email_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
