# Generated by Django 4.2.10 on 2024-02-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lessonmodel_coursemodel_lesson'),
        ('user', '0004_alter_user_age_alter_user_phone_alter_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.coursemodel'),
        ),
    ]
