# Generated by Django 4.2.10 on 2024-03-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_courses_user_starred_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='starred_courses',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='is_starred',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
